server:
  port: 8080
  context-path: /produto

teste: Tiago Teixeira profile DOCKER GITTTTTTT Teste

eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/

